version: "3.6"
networks:
    traefik:
        external:
            name: traefik
services:
    cutelab:
        image: dragas/thttpd
        restart: always
        volumes:
            - .:/var/www/http/:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik

            - traefik.http.routers.cutelab.rule=Host("cutelab.space")
            - traefik.http.routers.cutelab.entrypoints=websecure
            - traefik.http.routers.cutelab.service=cutelab
            - traefik.http.routers.cutelab.tls.certresolver=le
            - traefik.http.services.cutelab.loadbalancer.server.port=80

            - traefik.http.routers.cutelab-www.rule=Host("www.cutelab.space")
            - traefik.http.routers.cutelab-www.entrypoints=websecure
            - traefik.http.routers.cutelab-www.middlewares=cutelab-www
            - traefik.http.routers.cutelab-www.tls.certresolver=le
            - traefik.http.middlewares.cutelab-www.redirectregex.regex=^https?://(?:www\\.)?(.+)
            - traefik.http.middlewares.cutelab-www.redirectregex.replacement=https://$${1}
            - traefik.http.middlewares.cutelab-www.redirectregex.permanent=true

            - traefik.http.routers.flutterverse.rule=Host("flutterverse.com")
            - traefik.http.routers.flutterverse.entrypoints=websecure
            - traefik.http.routers.flutterverse.service=flutterverse
            - traefik.http.routers.flutterverse.tls.certresolver=le
            - traefik.http.services.flutterverse.loadbalancer.server.port=80

            - traefik.http.routers.flutterverse-www.rule=Host("www.flutterverse.com")
            - traefik.http.routers.flutterverse-www.entrypoints=websecure
            - traefik.http.routers.flutterverse-www.middlewares=flutterverse-www
            - traefik.http.routers.flutterverse-www.tls.certresolver=le
            - traefik.http.middlewares.flutterverse-www.redirectregex.regex=^https?://(?:www\\.)?(.+)
            - traefik.http.middlewares.flutterverse-www.redirectregex.replacement=https://$${1}
            - traefik.http.middlewares.flutterverse-www.redirectregex.permanent=true
        networks:
            - default
            - traefik
